print("Digite uma sequência de 3 números abaixo.")
num1 = int(input("Digite o primeiro número:"))
num2 = int(input("Digite o segundo número:"))
num3 = int(input("Digite o terceiro número:"))
print(f"Ordem inversa: {num3,num2,num1}")
